# 新入社員向けのフィードバックを投稿する対象
[view]
board_url = https://trello.com/b/9SxsLnD4/my-work
default_list = Archive

# 先輩社員向けのフィードバックを投稿する対象
[create]
board_url = https://trello.com/b/9SxsLnD4/my-work
default_list = おためしリスト
