# 履歴を取得するチャンネル・期間
[history]
# 履歴を確認するチャンネル名(表示名)
channel = AIビジネス連絡事項
# 履歴を取得する期間(今日から遡る日数)
read_date = 30

# チャンネルメンバー
[channel_users]
members = yano, endo, n-ishii, r-isahai, m-unno, r-asanoma, r-kinoshita, r-yurino

# GROUPSESSIONの新着記事を取得するフォーラム・期間
[groupsession]
# 監視対象フォーラムのID(「関東全体の情報共有」)
forum_sid = 15
# 何日前まで遡って新着記事を確認するか
read_date = 30
