# 履歴を取得するチャンネル・期間
[history]
# 履歴を確認するチャンネル名(表示名)
channel = AIビジネス連絡事項
# 履歴を取得する期間(今日から遡る日数)
read_date = 30

# チャンネルメンバー
[channel_users]
members = yano, endo, n-ishii, r-isahai, m-unno, r-asanoma, r-kinoshita, r-yurino
