## Mattermost
[mattermost]
# 動作確認用のDM送信先のユーザー名
target_username = r-kinoshita
# 履歴を取得するチャンネル・期間
[history]
# Mattermostタブで履歴を取得するチャンネル名(表示名)の初期値
channel = AIビジネス連絡事項
# 履歴を取得する期間(今日から遡る日数)の初期値
read_date = 30
# チャンネルメンバー
# :sumi:が押されているかを確認してメンションする対象
[channel_users]
members = yano, endo, n-ishii, r-isahai, m-unno, r-asanoma, r-kinoshita, r-yurino

## GROUPSESSION
[groupsession]
# 監視対象フォーラムのID
# 全社連絡用 : 5, 関東全体の情報共有 : 15
forum_sid = 5, 15
# 新着記事を取得する期間(今日から遡る日数)の初期値
read_date = 30
# リマインドの投稿先チャンネル(表示名)
remind_channel = AIビジネス連絡事項, AIC 連絡事項

## GROWI(社内wiki)へのアジェンダ公開先
[growi]
# 全体共有事項作成時に確認するMattermostのチャンネル
channel_list = AIビジネス連絡事項, AIC 連絡事項
# アジェンダを配置する親ページのパス(この下に "年/月" のページが作成・更新される)
# root_path = /2000_開発者向け/2000_開発者向け/2YYY_組織/AIビジネス研究室/100_AIM
root_path = /user/r-kinoshita/アジェンダ
