# -*- coding: utf-8 -*-
"""データサイエンス基礎ドリル - 第2章以降の教材定義

このファイルの EXTRA_LESSONS を増やすだけで、フロントエンドとAPIに
自動反映されます。main.py が curriculum.LESSONS と連結して使います。
"""

EXTRA_LESSONS = [
    # ================= 第2章 リストと辞書 =================
    {
        "id": "l2-1",
        "chapter": 2,
        "chapter_title": "リストと辞書",
        "order": 1,
        "title": "リストを操る",
        "minutes": 45,
        "status": "open",
        "summary": "値の並び「リスト」の基本。0から始まる番号（索引）、切り出し、追加、個数まで自在に扱えるようにします。",
        "explanation": [
            "リストは `[値, 値, ...]` のように値を並べて持てる「箱」です。",
            "中の値を取り出すときは `リスト[番号]`。**番号は0から始まる**のが最大のポイントです。",
            "`リスト[開始:終了]` で一部を切り出せます（スライス）。`終了` の番号は含まれません。",
            "`リスト.append(値)` で末尾に追加、`len(リスト)` で個数が分かります。",
        ],
        "keypoints": [
            "取り出し: `リスト[0]` は最初の要素（0から始まる）",
            "末尾: `リスト[-1]` は最後の要素",
            "切り出し: `リスト[1:4]` は番号1〜3（4は含まない）",
            "追加: `リスト.append(値)` / 個数: `len(リスト)`",
        ],
        "example": 'menus = ["コーヒー", "紅茶", "ラテ"]\nprint(menus[0])     # コーヒー\nprint(menus[-1])    # ラテ（後ろから1番目）\nprint(menus[1:3])   # ["紅茶", "ラテ"]',
        "example_output": "コーヒー\nラテ\n['紅茶', 'ラテ']",
        "drills": [
            {
                "id": "d2-1-1", "type": "code_gap",
                "title": "2番目の要素を取り出そう",
                "question": "items = [\"ペン\", \"ノート\", \"消しゴム\"] から「ノート」を取り出して表示してください。番号に注意（0から数えます）。",
                "starter": 'items = ["ペン", "ノート", "消しゴム"]\nprint(items[____])',
                "hint": "ペン=0、ノート=1、消しゴム=2 です。",
                "expected": ["ノート"],
            },
            {
                "id": "d2-1-2", "type": "code_gap",
                "title": "一部を切り出そう（スライス）",
                "question": "nums = [10, 20, 30, 40, 50] から [20, 30, 40] を取り出して表示してください。",
                "starter": "nums = [10, 20, 30, 40, 50]\nprint(nums[____])",
                "hint": "20(番号1) から 40(番号3) まで。終了の番号は「4」にします（4は含まれない）。",
                "expected": ["[20, 30, 40]"],
            },
            {
                "id": "d2-1-3", "type": "code_gap",
                "title": "末尾に要素を追加しよう",
                "question": "nums の末尾に 4 を追加して [1, 2, 3, 4] にしてください。メソッド名を書きます。",
                "starter": "nums = [1, 2, 3]\nnums.____(4)\nprint(nums)",
                "hint": "「加える」を意味する英語のメソッド名です。addではなく……。",
                "expected": ["[1, 2, 3, 4]"],
            },
            {
                "id": "d2-1-4", "type": "code_gap",
                "title": "要素の個数を数えよう",
                "question": "words = [\"a\", \"b\", \"c\"] の要素の個数（3）を表示してください。個数を返す組み込み関数を使います。",
                "starter": 'words = ["a", "b", "c"]\nprint(____(words))',
                "hint": "「長さ」を返す関数。文字列の長さを調べるときにも使います。",
                "expected": ["3"],
            },
            {
                "id": "d2-1-5", "type": "quiz",
                "title": "マイナスの番号",
                "question": "nums = [7, 8, 9] のとき、nums[-1] は何を指しますか？",
                "choices": ["7（最初）", "8（真ん中）", "9（最後）", "エラーになる"],
                "answer_index": 2,
                "feedback": "負の番号は「後ろから」数えます。nums[-1] は末尾の 9 です。末尾を取り出すときによく使います。",
            },
        ],
    },
    {
        "id": "l2-2",
        "chapter": 2,
        "chapter_title": "リストと辞書",
        "order": 2,
        "title": "辞書でキーと値",
        "minutes": 45,
        "status": "open",
        "summary": "「名前 → 値」の対応表「辞書（dict）」。データ分析では最も使うデータ構造です。",
        "explanation": [
            "辞書は `{\"キー\": 値, ...}` の形で、キーから値を瞬時に取り出せます。",
            "値の取り出しは `辞書[\"キー\"]`。リストの番号の代わりに「名前」で探します。",
            "新しいキーを追加するときも `辞書[\"キー\"] = 値` と書くだけでOK。",
            "`辞書.items()` でキーと値のペア、`辞書.keys()` / `辞書.values()` でキー・値だけを取り出せます。",
        ],
        "keypoints": [
            "作る: `menu = {\"コーヒー\": 350}`（キー：値）",
            "取り出す: `menu[\"コーヒー\"]` → 350",
            "追加/更新: `menu[\"ラテ\"] = 400`",
            "ループ: `for k, v in 辞書.items():`",
        ],
        "example": 'menu = {"コーヒー": 350, "紅茶": 300}\nmenu["ラテ"] = 400\nprint(menu["コーヒー"])\nfor name, price in menu.items():\n    print(name, price)',
        "example_output": "350\nコーヒー 350\n紅茶 300\nラテ 400",
        "drills": [
            {
                "id": "d2-2-1", "type": "code_gap",
                "title": "キーから値を取り出そう",
                "question": "menu = {\"コーヒー\": 350, \"紅茶\": 300, \"ラテ\": 400} から「紅茶」の値（300）を表示してください。",
                "starter": 'menu = {"コーヒー": 350, "紅茶": 300, "ラテ": 400}\nprint(menu[____])',
                "hint": "キーは文字列なので引用符で囲みます。メニュー名そのものをキーにします。",
                "expected": ["300"],
            },
            {
                "id": "d2-2-2", "type": "code_gap",
                "title": "新しいキーを追加しよう",
                "question": "score に「理科: 70」を追加した状態で表示してください（国語・数学は既にあります）。",
                "starter": 'score = {"国語": 80, "数学": 90}\nscore[____] = 70\nprint(score)',
                "hint": "追加したいキーの名前（科目）を引用符で囲んで入れます。",
                "expected": ["{'国語': 80, '数学': 90, '理科': 70}"],
            },
            {
                "id": "d2-2-3", "type": "code_gap",
                "title": "値を全部足してみよう",
                "question": "3店舗の売上を合計（3500）して表示してください。values() を使うと値をまとめて取り出せます。",
                "starter": 'sales = {"A店": 1200, "B店": 800, "C店": 1500}\ntotal = 0\nfor v in sales.____():\n    total += v\nprint(total)',
                "hint": "「値」を英語で。キーを取り出したいときは keys() です。",
                "expected": ["3500"],
            },
            {
                "id": "d2-2-4", "type": "quiz",
                "title": "同じキーを2回書いたら",
                "question": "d = {\"a\": 1, \"a\": 2} を実行すると、d の中身はどうなりますか？",
                "choices": ["{\"a\": 1, \"a\": 2}（両方残る）", "{\"a\": 1}（最初が残る）", "{\"a\": 2}（後からが上書き）", "エラーになる"],
                "answer_index": 2,
                "feedback": "辞書のキーは重複できず、後から書いた値で上書きされます（キーは一意）。実務で辞書を作るときは重複に要注意。",
            },
            {
                "id": "d2-2-5", "type": "code_gap",
                "title": "キーが入っているか調べよう",
                "question": "「コーヒー」が menu のキーにあるか調べて、True を表示してください。メンバー確認の演算子を書きます。",
                "starter": 'menu = {"コーヒー": 350}\nprint("コーヒー" ____ menu)',
                "hint": "「〜の中に含まれるか」を表す、たった2文字の演算子です。",
                "expected": ["True"],
            },
        ],
    },
    # ================= 第3章 関数とモジュール =================
    {
        "id": "l3-1",
        "chapter": 3,
        "chapter_title": "関数とモジュール",
        "order": 1,
        "title": "処理を部品にして再利用",
        "minutes": 60,
        "status": "open",
        "summary": "def で関数を作り、同じ処理を何度でも呼べるようにします。実務のコードは関数の集まりです。",
        "explanation": [
            "関数は「処理のかたまり」に名前を付けたものです。`def 名前():` で定義し、`名前()` で呼び出します。",
            "関数は値を受け取って（引数）、結果を返すことができます（return）。",
            "「計算して結果を返す」関数は return で値を返し、「画面に出す」関数は print を使います。",
            "`import math` のように読み込むのが「モジュール」。Pythonの強力な機能はここに詰まっています。",
        ],
        "keypoints": [
            "定義: `def 名前(引数):` の次の行から字下げして処理を書く",
            "呼び出し: `名前(引数)`（引数がない関数は `名前()`）",
            "結果を返す: `return 値`（return しない関数の戻り値は None）",
            "モジュール: `import math` → `math.sqrt(16)`",
        ],
        "example": 'def tax(price):\n    return price * 1.1\n\nprint(tax(1200))\nprint(tax(500))',
        "example_output": "1320.0\n550.0",
        "drills": [
            {
                "id": "d3-1-1", "type": "code_gap",
                "title": "関数を呼び出そう",
                "question": "定義済みの関数 greet() を呼び出して「こんにちは」を表示してください。",
                "starter": 'def greet():\n    print("こんにちは")\n\n____()',
                "hint": "関数名のあとに括弧を付けて呼び出します。",
                "expected": ["こんにちは"],
            },
            {
                "id": "d3-1-2", "type": "code_gap",
                "title": "return で結果を返そう",
                "question": "税込価格を返す関数 tax(price) で、結果を返すための命令を補ってください（print(tax(1200)) で 1320.0 と表示されるように）。",
                "starter": "def tax(price):\n    ____ price * 1.1\n\nprint(tax(1200))",
                "hint": "「値を返す」ためのキーワードです。print との違いに注意。",
                "expected": ["1320.0"],
            },
            {
                "id": "d3-1-3", "type": "code_gap",
                "title": "引数を受け取る関数を呼ぼう",
                "question": "定義済みの average(a, b) を呼んで、10 と 30 の平均（20.0）を表示してください。",
                "starter": "def average(a, b):\n    return (a + b) / 2\n\nprint(____(10, 30))",
                "hint": "関数名を書き、引数をカンマ区切りで渡します。",
                "expected": ["20.0"],
            },
            {
                "id": "d3-1-4", "type": "quiz",
                "title": "return がない関数の戻り値",
                "question": "次の関数を実行したとき、x に入る値は？\ndef show():\n    print(\"こんにちは\")\nx = show()",
                "choices": ["こんにちは", "None", "\"こんにちは\"", "エラーになる"],
                "answer_index": 1,
                "feedback": "return がない関数は何も返さず、戻り値は特別な値 None になります。「表示する」役割の関数と「計算結果を返す」関数は別物と覚えましょう。",
            },
            {
                "id": "d3-1-5", "type": "code_gap",
                "title": "モジュールを使う",
                "question": "math モジュールの sqrt 関数で、16 の平方根（4.0）を表示してください。",
                "starter": "import math\nprint(math.____(16))",
                "hint": "「平方根」を表す英単語です（square root）。",
                "expected": ["4.0"],
            },
            {
                "id": "d3-1-6", "type": "quiz",
                "title": "引数なしの関数",
                "question": "def greet(): のように引数の括弧が空の関数は、どう呼び出せばよいですか？",
                "choices": ["greet（括弧なし）", "greet()（空の括弧）", "greet[]（角括弧）", "define greet"],
                "answer_index": 1,
                "feedback": "引数がなくても、呼び出すときは必ず空の括弧 greet() を付けます。括弧を忘れると「関数の中身」ではなく「関数そのもの」を参照してしまいます。",
            },
        ],
    },
    # ================= 第4章 pandas で表データ処理 =================
    {
        "id": "l4-1",
        "chapter": 4,
        "chapter_title": "pandas で表データ処理",
        "order": 1,
        "title": "DataFrame のきほん",
        "minutes": 60,
        "status": "open",
        "summary": "データ分析の主役、pandas。表データ（DataFrame）の読み込み・列の合計・平均・条件抽出を練習します。",
        "explanation": [
            "pandas は表データを扱うためのライブラリです。`import pandas as pd` と読み込みます。",
            "CSVを読むと「DataFrame」という表になります。列は `df[\"列名\"]` で取り出せます。",
            "`df[\"売上\"].sum()` で合計、`.mean()` で平均、`.count()` で件数が得られます。",
            "条件で絞るのも DataFrame の得意技。`df[\"売上\"] >= 1500` が「真の行だけ」を選びます。",
        ],
        "keypoints": [
            "読込み: `df = pd.read_csv(\"ファイル名.csv\")`",
            "行数: `len(df)` / 先頭を見る: `df.head()`",
            "列の統計: `df[\"列\"].sum()` / `.mean()` / `.min()` / `.max()`",
            "条件抽出: `df[df[\"売上\"] >= 1500]`（条件を満たす行だけ）",
        ],
        "example": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(len(df))\nprint(df["売上"].sum())\nprint(df["売上"].mean())',
        "example_output": "60\n105330\n1755.5",
        "drills": [
            {
                "id": "d4-1-1", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "データの行数を調べよう",
                "question": "sales.csv を読み込んだ df の行数（60）を表示してください。行数を返す組み込み関数を使います。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(____)',
                "hint": "リストや文字列の長さを調べる関数と同じものです。",
                "expected": ["60"],
            },
            {
                "id": "d4-1-2", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "売上の合計を出そう",
                "question": "「売上」列の合計（105330）を表示してください。列を取り出して合計を求めます。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(df["売上"].____())',
                "hint": "「合計」を英語で。列に .○○() と付けて計算します。",
                "expected": ["105330"],
            },
            {
                "id": "d4-1-3", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "売上の平均を出そう",
                "question": "「売上」列の平均（1755.5）を表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(____)',
                "hint": "列を取り出して .mean() を付けます。",
                "expected": ["1755.5"],
            },
            {
                "id": "d4-1-4", "type": "quiz",
                "title": "列の取り出し方",
                "question": "df[\"売上\"] は何を取り出しますか？",
                "choices": ["売上列のデータ（Series）", "表全体（DataFrame）", "売上が大きい順に並べた表", "1行目のデータ"],
                "answer_index": 0,
                "feedback": "df[\"列名\"] は1つの列を表す Series を取り出します。複数列が必要なら df[[\"列1\", \"列2\"]] のように2重ブラケットにします。",
            },
            {
                "id": "d4-1-5", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "条件で行を絞る",
                "question": "売上が 1500 円以上のデータが何件あるか（34）を表示してください。条件式を bool に直して合計するのがコツです。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint((____).sum())',
                "hint": "売上列と 1500 を比較します。比較の結果は True/False の並びになり、.sum() で True の件数が得られます。",
                "expected": ["34"],
            },
        ],
    },
    {
        "id": "l4-2",
        "chapter": 4,
        "chapter_title": "pandas で表データ処理",
        "order": 2,
        "title": "集計と抽出",
        "minutes": 60,
        "status": "open",
        "summary": "groupby による「グループごとの集計」と、条件を組み合わせた抽出。データ分析の仕事の中心です。",
        "explanation": [
            "`df.groupby(\"商品\")[\"売上\"].sum()` は「商品ごとの売上合計」を計算します。",
            "集計結果から一番大きいものは `.idxmax()`（名前）・`.max()`（値）で取り出せます。",
            "`df[df[\"商品\"] == \"抹茶ラテ\"]` のように、条件式で「特定のグループだけ」に絞ることもできます。",
            "groupby の後は `.sum()` だけでなく `.mean()` もよく使います。",
        ],
        "keypoints": [
            "グループ集計: `df.groupby(\"列\")[\"値列\"].sum()`",
            "最大の名前: `.idxmax()` / 最大の値: `.max()`",
            "絞り込み: `df[df[\"列\"] == \"値\"]`",
            "応用: `.mean()` でグループごとの平均",
        ],
        "example": "item = df.groupby(\"商品\")[\"売上\"].sum()\nprint(item.idxmax())\nprint(item.max())",
        "example_output": "アイスコーヒー\n24250",
        "drills": [
            {
                "id": "d4-2-1", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "売上が一番多い商品",
                "question": "商品ごとの売上合計いちばん多い「商品名」を表示してください（答え: アイスコーヒー）。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nitem = df.groupby("商品")["売上"].sum()\nprint(____)',
                "hint": "「最大値を持つインデックス（名前）」を返すメソッドです。max ではなくこちら。",
                "expected": ["アイスコーヒー"],
            },
            {
                "id": "d4-2-2", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "特定の商品に絞って合計",
                "question": "「抹茶ラテ」だけに絞った売上合計（9420）を表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\ntea = df[____]\nprint(tea["売上"].sum())',
                "hint": "商品列と「抹茶ラテ」の比較で True/False の条件を作ります。文字列は引用符で囲みます。",
                "expected": ["9420"],
            },
            {
                "id": "d4-2-3", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "月ごとの売上合計",
                "question": "「月」ごとの売上合計を出し、そのうち 1 月の値（11030）を表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nmonth = df.groupby("月")["売上"].sum()\nprint(month[____])',
                "hint": "month は「月 → 合計」の並び。1月の合計は month[1] で取り出せます。",
                "expected": ["11030"],
            },
            {
                "id": "d4-2-4", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "カテゴリごとの平均売上",
                "question": "「ドリンク」カテゴリの売上平均（1971.7）を、round(数値, 1) で小数1桁に丸めて表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nd = df[df["カテゴリ"] == "ドリンク"]\nprint(____)',
                "hint": "d の売上列の平均を取り、round( ..., 1) で丸めます。",
                "expected": ["1971.7"],
            },
            {
                "id": "d4-2-5", "type": "quiz",
                "title": "groupby の返り値",
                "question": "df.groupby(\"カテゴリ\")[\"売上\"].sum() の結果は何ですか？",
                "choices": ["カテゴリごとの売上合計の表（Series）", "1つの数字", "カテゴリ別の行数リスト", "元の表と同じ形"],
                "answer_index": 0,
                "feedback": "「カテゴリ（グループ名）→ 合計値」の対応が1本の Series（表）として返ります。これを idxmax() や [\"ドリンク\"] で取り出して使います。",
            },
        ],
    },
    # ================= 第5章 可視化と統計のきほん =================
    {
        "id": "l5-1",
        "chapter": 5,
        "chapter_title": "可視化と統計のきほん",
        "order": 1,
        "title": "グラフでデータを語る",
        "minutes": 45,
        "status": "open",
        "summary": "matplotlib で折れ線グラフ・棒グラフを描き、データの動きや傾向を「目で」捉えます。",
        "explanation": [
            "matplotlib はグラフを描くライブラリ。`import matplotlib.pyplot as plt` で使います。",
            "折れ線は `plt.plot(データ)`、棒グラフは `plt.bar(位置, 値)`。",
            "`plt.title(\"タイトル\")` でタイトルを付け、`plt.show()` で表示します。",
            "コードを実行すると画面に図が描かれます（実行環境によっては下に画像で表示）。",
        ],
        "keypoints": [
            "折れ線: `plt.plot(データ)`",
            "棒グラフ: `plt.bar(横軸, 縦軸)`",
            "タイトル: `plt.title(\"…\")` / 表示: `plt.show()`",
            "実行すると図が表示される（採点は「エラーなしで図ができたか」）",
        ],
        "example": 'import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("sales.csv")\nmonth = df.groupby("月")["売上"].sum()\nplt.plot(month)\nplt.title("月別売上")\nplt.show()',
        "example_output": "（折れ線グラフが表示されます）",
        "drills": [
            {
                "id": "d5-1-1", "type": "viz", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "売上の推移を折れ線で",
                "question": "月ごとの売上合計を「折れ線グラフ」で描いてください。空欄にはグラフを描くメソッド名を入れます。実行したら採点して、図が出るか確かめましょう。",
                "starter": 'import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("sales.csv")\nmonth = df.groupby("月")["売上"].sum()\nplt.____(month)\nplt.title("月別売上")\nplt.show()',
                "hint": "「線を引く」メソッドです。plot とほぼ同じつづり。",
            },
            {
                "id": "d5-1-2", "type": "viz", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "商品別の売上を棒で",
                "question": "商品ごとの売上合計を「棒グラフ」で描いてください。横軸は商品名、縦軸は売上合計です。",
                "starter": 'import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("sales.csv")\nitem = df.groupby("商品")["売上"].sum()\nplt.____(item.index, item.values)\nplt.title("商品別売上")\nplt.show()',
                "hint": "棒グラフを描くメソッド（bar から始まる）です。横軸に名前、縦軸に値を渡します。",
            },
            {
                "id": "d5-1-3", "type": "quiz",
                "title": "折れ線グラフが向く場面",
                "question": "月ごとの売上の「推移（時間の流れ）」を見たいとき、最も向いているグラフはどれ？",
                "choices": ["折れ線グラフ", "円グラフ", "ヒストグラム", "散布図"],
                "answer_index": 0,
                "feedback": "時間の経過に沿った変化は折れ線グラフが定番。構成比を見るのが円グラフ、分布を見るのがヒストグラム、2変数の関係が散布図です。",
            },
        ],
    },
    {
        "id": "l5-2",
        "chapter": 5,
        "chapter_title": "可視化と統計のきほん",
        "order": 2,
        "title": "統計のきほん",
        "minutes": 45,
        "status": "open",
        "summary": "平均・最大・度数（該当数）・相関という、データを数字で語る道具を身につけます。",
        "explanation": [
            "1日ずつの気温データ（temps.csv）を題材に、統計の基本を練習します。",
            "`df[\"列\"].mean()` は平均、`.max()` は最大値。",
            "「条件を満たす行数」= 度数のカウントは、条件式 + `.sum()`（または `(条件).sum()`）。",
            "2つの列の関係（相関）は `df[\"a\"].corr(df[\"b\"])`。1に近いほど「一緒に動く」正の相関、-1に近いほど逆の動き。",
        ],
        "keypoints": [
            "平均: `.mean()` / 最大: `.max()`",
            "度数の数え方: `(df[\"列\"] >= 30).sum()`",
            "相関: `df[\"a\"].corr(df[\"b\"])`（-1〜1）",
            "相関 0.99 は「非常に強い正の相関」",
        ],
        "example": 'import pandas as pd\n\nt = pd.read_csv("temps.csv")\nprint(t["最高気温"].mean())\nprint((t["最高気温"] >= 30).sum())',
        "example_output": "15.9\n55",
        "drills": [
            {
                "id": "d5-2-1", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["temps.csv"],
                "title": "真夏日の日数を数えよう",
                "question": "最高気温が 30 度以上の「日数」（55日）を表示してください。条件式を True/False の並びにして .sum() します。",
                "starter": 'import pandas as pd\n\nt = pd.read_csv("temps.csv")\nprint((t["最高気温"] ____ 30).sum())',
                "hint": "「以上」の比較演算子です。",
                "expected": ["55"],
            },
            {
                "id": "d5-2-2", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["temps.csv"],
                "title": "平均最高気温を出そう",
                "question": "最高気温の平均（15.9）を小数1桁に丸めて表示してください。",
                "starter": 'import pandas as pd\n\nt = pd.read_csv("temps.csv")\nprint(____)',
                "hint": "列の平均を round(数値, 1) で丸めます。",
                "expected": ["15.9"],
            },
            {
                "id": "d5-2-3", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["temps.csv"],
                "title": "最高気温と最低気温の関係",
                "question": "最高気温と最低気温の「相関係数」（0.99）を小数2桁まで表示してください。",
                "starter": 'import pandas as pd\n\nt = pd.read_csv("temps.csv")\nprint(round(____, 2))',
                "hint": "2つの列の関係を数値にするメソッド（corr で始まる）です。",
                "expected": ["0.99"],
            },
            {
                "id": "d5-2-4", "type": "viz", "requires": ["pandas"],
                "data_files": ["temps.csv"],
                "title": "最高気温と最低気温の散布図",
                "question": "横軸を最低気温、縦軸を最高気温にした「散布図」を描いてください。2つの変数の関係を見るときの定番です。",
                "starter": 'import pandas as pd\nimport matplotlib.pyplot as plt\n\nt = pd.read_csv("temps.csv")\nplt.____(t["最低気温"], t["最高気温"])\nplt.xlabel("最低気温")\nplt.ylabel("最高気温")\nplt.show()',
                "hint": "「点をまき散らす」メソッド（scatter です）。",
            },
            {
                "id": "d5-2-5", "type": "quiz",
                "title": "相関係数 0.99 の読み方",
                "question": "最高気温と最低気温の相関係数が 0.99 のとき、どんなことが言えますか？",
                "choices": ["ほぼ無関係", "強い正の相関（一緒に上がる/下がる）", "強い負の相関（逆に動く）", "数値が間違い（必ず -1〜1 の中）"],
                "answer_index": 1,
                "feedback": "1に非常に近いので、「最高気温が高い日は最低気温も高い」という強い正の相関。夏は日の出前も暖かく、冬は真冬の朝も寒い、という直感と一致します。",
            },
        ],
    },
    # ================= 第6章 総合ドリル =================
    {
        "id": "l6-1",
        "chapter": 6,
        "chapter_title": "総合ドリル",
        "order": 1,
        "title": "売上データ分析（実務風ケース）",
        "minutes": 90,
        "status": "open",
        "summary": "講座の集大成。あなたはカフェチェーンのデータ分析担当。sales.csv を使い「読み込み → 集計 → 可視化 → 報告」まで一気通貫でこなします。",
        "explanation": [
            "【設定】あなたはカフェチェーン「ドリル珈琲」のデータ分析担当です。1年分の売上データ sales.csv を渡されました。",
            "店長からの依頼は次の4つです。1) 年間売上はいくらか 2) 売上が1500円以上の会計は何件か 3) ドリンクの平均売上はいくらか 4) 月別売上の折れ線グラフを作ってほしい。",
            "最後に、「売れ筋を一言で」まとめるレポートを提出します。ここまで学んだことを全部使うので、分からなければ前の章に戻ってOKです。",
        ],
        "keypoints": [
            "pd.read_csv で読み込み → 各ステップを順番に解く",
            "集計: sum / mean / 条件抽出",
            "可視化: plt.plot + plt.show",
            "最後にレポート（自由記述）を提出",
        ],
        "example": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(df["売上"].sum())',
        "example_output": "105330",
        "drills": [
            {
                "id": "d6-1-1", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "依頼① 年間売上はいくら？",
                "question": "年間の売上合計を表示してください。店長に報告する最初の数字です。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint(df["売上"].____())',
                "hint": "合計を出すメソッドです。",
                "expected": ["105330"],
            },
            {
                "id": "d6-1-2", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "依頼② 高額会計は何件？",
                "question": "売上が 1500 円以上の会計の「件数」を表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nprint((df["売上"] >= 1500).____())',
                "hint": "True/False の並びを足し合わせて件数にします。",
                "expected": ["34"],
            },
            {
                "id": "d6-1-3", "type": "code_gap", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "依頼③ ドリンクの平均売上",
                "question": "「ドリンク」カテゴリの売上平均（1971.7）を小数1桁に丸めて表示してください。",
                "starter": 'import pandas as pd\n\ndf = pd.read_csv("sales.csv")\nd = df[df["カテゴリ"] == "ドリンク"]\nprint(round(d["売上"].mean(), 1))',
                "hint": "このコードはほぼ完成しています。実行して、正しい数字が出るか確かめましょう。",
                "expected": ["1971.7"],
            },
            {
                "id": "d6-1-4", "type": "viz", "requires": ["pandas"],
                "data_files": ["sales.csv"],
                "title": "依頼④ 月別売上のグラフ",
                "question": "月ごとの売上合計を「折れ線グラフ」にして、タイトル「月別売上」を付けてください。店長に「夏と冬に売上が伸びる」と伝えるための図です。",
                "starter": 'import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("sales.csv")\nmonth = df.groupby("月")["売上"].sum()\nplt.____(month)\nplt.title("月別売上")\nplt.show()',
                "hint": "折れ線を描くメソッド名です。",
            },
            {
                "id": "d6-1-5", "type": "report",
                "title": "最終課題 店長への報告",
                "question": "【レポート】店長に分かりやすく報告するため、下の1〜3を1文ずつ書いて提出してください。\n1) 年間売上はいくらですか？\n2) 売れ筋（売上上位）はどの商品ですか？\n3) 店長への「次のおすすめ施策」を一言で。",
                "placeholder": "例: 年間売上は 105,330円 でした。売れ筋はアイスコーヒーで、売上上位はドリンク類でした。夏のアイスドリンク強化が次の施策に効くと思います。",
            },
        ],
    },
]
